# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 'Frontend Build Pipeline'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - frontend/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'NPM install'
  inputs:
    command: 'install'
    workingDir: '$(Build.BinariesDirectory)/frontend'
- task: Npm@1
  displayName: 'NPM Build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.BinariesDirectory)/frontend'
    customCommand: 'run ci-build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/frontend/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'frontend'
    publishLocation: 'Container'