# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Backend Build Pipeline'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - backend/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
steps:
- task: UseDotNet@2
  displayName: 'Download .NET Core'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: DotNetCoreCLI@2
  displayName: '.NET Core Build'
  inputs:
    command: 'build'
    projects: './backend/MasksUnleashed.API/MasksUnleashed.API.csproj'
- task: DotNetCoreCLI@2
  displayName: ".NET Core Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r win-x86 --self-contained true --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory).zip'
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'demo'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Testproject'
    cliProjectName: 'Testproject'
    cliSources: './backend/MasksUnleashed.API'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifact to Deployment Container"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory).zip'
    ArtifactName: 'backend'
    publishLocation: 'Container'